// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package postgres

var TableNames = struct {
	AccountLog              string
	AuditEvent              string
	Candle                  string
	CMCLatestListing        string
	Currency                string
	CurrencyPair            string
	CurrencyPairStrategy    string
	Datahistoryjob          string
	Datahistoryjobrelations string
	Datahistoryjobresult    string
	Exchange                string
	Gateiocoin              string
	GooseDBVersion          string
	LiveOrder               string
	LiveTrade               string
	Script                  string
	ScriptExecution         string
	Strategy                string
	Trade                   string
	WithdrawalCrypto        string
	WithdrawalFiat          string
	WithdrawalHistory       string
}{
	AccountLog:              "account_log",
	AuditEvent:              "audit_event",
	Candle:                  "candle",
	CMCLatestListing:        "cmc_latest_listing",
	Currency:                "currency",
	CurrencyPair:            "currency_pair",
	CurrencyPairStrategy:    "currency_pair_strategy",
	Datahistoryjob:          "datahistoryjob",
	Datahistoryjobrelations: "datahistoryjobrelations",
	Datahistoryjobresult:    "datahistoryjobresult",
	Exchange:                "exchange",
	Gateiocoin:              "gateiocoin",
	GooseDBVersion:          "goose_db_version",
	LiveOrder:               "live_order",
	LiveTrade:               "live_trade",
	Script:                  "script",
	ScriptExecution:         "script_execution",
	Strategy:                "strategy",
	Trade:                   "trade",
	WithdrawalCrypto:        "withdrawal_crypto",
	WithdrawalFiat:          "withdrawal_fiat",
	WithdrawalHistory:       "withdrawal_history",
}
