// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package postgres

var TableNames = struct {
	AuditEvent              string
	Candle                  string
	Datahistoryjob          string
	Datahistoryjobrelations string
	Datahistoryjobresult    string
	Exchange                string
	GooseDBVersion          string
	LiveOrder               string
	LiveTrade               string
	Script                  string
	ScriptExecution         string
	Trade                   string
	WithdrawalCrypto        string
	WithdrawalFiat          string
	WithdrawalHistory       string
}{
	AuditEvent:              "audit_event",
	Candle:                  "candle",
	Datahistoryjob:          "datahistoryjob",
	Datahistoryjobrelations: "datahistoryjobrelations",
	Datahistoryjobresult:    "datahistoryjobresult",
	Exchange:                "exchange",
	GooseDBVersion:          "goose_db_version",
	LiveOrder:               "live_order",
	LiveTrade:               "live_trade",
	Script:                  "script",
	ScriptExecution:         "script_execution",
	Trade:                   "trade",
	WithdrawalCrypto:        "withdrawal_crypto",
	WithdrawalFiat:          "withdrawal_fiat",
	WithdrawalHistory:       "withdrawal_history",
}
