// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package postgres

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("AuditEvents", testAuditEventsUpsert)

	t.Run("Candles", testCandlesUpsert)

	t.Run("Datahistoryjobs", testDatahistoryjobsUpsert)

	t.Run("Datahistoryjobresults", testDatahistoryjobresultsUpsert)

	t.Run("Exchanges", testExchangesUpsert)

	t.Run("GooseDBVersions", testGooseDBVersionsUpsert)

	t.Run("Scripts", testScriptsUpsert)

	t.Run("ScriptExecutions", testScriptExecutionsUpsert)

	t.Run("Trades", testTradesUpsert)

	t.Run("WithdrawalCryptos", testWithdrawalCryptosUpsert)

	t.Run("WithdrawalFiats", testWithdrawalFiatsUpsert)

	t.Run("WithdrawalHistories", testWithdrawalHistoriesUpsert)
}
